function position = leg_position(phi1,phi4)
%LEG_POSITION
%    POSITION = LEG_POSITION(PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-01-19 14:01:43

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = t2.*(2.1e+1./1.0e+2);
t7 = t3.*(2.1e+1./1.0e+2);
t8 = t2.*(2.1e+1./2.0e+2);
t9 = t3.*(2.1e+1./2.0e+2);
t10 = t4.*(2.1e+1./1.0e+2);
t11 = t5.*(2.1e+1./1.0e+2);
t12 = t4.*(2.1e+1./2.0e+2);
t13 = t5.*(2.1e+1./2.0e+2);
t14 = -t7;
t15 = -t8;
t16 = -t9;
t17 = -t11;
t18 = -t12;
t19 = -t13;
t20 = t6+t14;
t21 = t8+t16;
t22 = t10+t17;
t23 = t12+t19;
t24 = t20.^2;
t25 = t21.^2;
t26 = t22.^2;
t27 = t23.^2;
t28 = t24+t26;
t29 = t28.^2;
t31 = t9+t15+t28;
t30 = -t29;
t32 = 1.0./t31;
t33 = t25+t27+t30;
t34 = sqrt(t33);
t35 = t13+t18+t34;
t36 = t32.*t35;
t37 = atan(t36);
t38 = t37.*2.0;
t39 = cos(t38);
t40 = sin(t38);
t41 = t39./4.0;
position = [sqrt((t10+t40./4.0).^2+(t6+t41).^2),atan2(t4.*(2.1e+1./1.0e+2)+t40./4.0,t6+t41)];
end
