/*
 * File: leg_position.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 2025-12-14 14:58:52
 */

/* Include Files */
#include "leg_position.h"
#include "atan2.h"
#include "leg_position_data.h"
#include "leg_position_initialize.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_POSITION
 *     POSITION = LEG_POSITION(PHI1,PHI4)
 *
 * Arguments    : double phi1
 *                double phi4
 *                double position[2]
 * Return Type  : void
 */
void leg_position(double phi1, double phi4, double position[2])
{
  double a;
  double b_a;
  double t10;
  double t11;
  double t12;
  double t2;
  double t3;
  double t4;
  double t5;
  double t7;
  if (!isInitialized_leg_position) {
    leg_position_initialize();
  }
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-12-14 14:52:54 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t7 = t2 * 0.16;
  t10 = t4 * 0.08;
  t11 = t4 * 0.16;
  t12 = t5 * 0.08;
  a = t10 - t12;
  t5 = t11 - t5 * 0.16;
  b_a = (t3 * 0.16 - t7) + 0.105;
  t4 = (t3 * 0.08 - t2 * 0.08) + 0.0525;
  t5 = t5 * t5 + b_a * b_a;
  t4 = atan(1.0 / (t4 + t5) *
            ((t12 - t10) + sqrt((a * a + t4 * t4) - t5 * t5))) *
       2.0;
  t5 = t11 + sin(t4) / 4.0;
  t4 = (t7 + cos(t4) / 4.0) - 0.0525;
  position[0] = sqrt(t5 * t5 + t4 * t4);
  position[1] = b_atan2(t5, t4);
}

/*
 * File trailer for leg_position.c
 *
 * [EOF]
 */
