/*
 * File: leg_force.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 2025-12-14 14:55:35
 */

/* Include Files */
#include "leg_force.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_FORCE
 *     T = LEG_FORCE(F,Tp,PHI1,PHI4)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi4
 *                double T[2]
 * Return Type  : void
 */
void leg_force(double F, double Tp, double phi1, double phi4, double T[2])
{
  double t120;
  double t123_tmp;
  double t124_tmp;
  double t131_tmp;
  double t16_tmp;
  double t174;
  double t175;
  double t17_tmp;
  double t180_tmp;
  double t18_tmp;
  double t19_tmp;
  double t20_tmp;
  double t21_tmp;
  double t22_tmp;
  double t23_tmp;
  double t47_tmp;
  double t48_tmp;
  double t54_tmp;
  double t55_tmp;
  double t5_tmp;
  double t77_tmp;
  double t7_tmp;
  double t96;
  double t98_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-12-14 14:52:55 */
  t96 = cos(phi1);
  t5_tmp = cos(phi4);
  t175 = sin(phi1);
  t7_tmp = sin(phi4);
  t16_tmp = t96 * 0.08;
  t17_tmp = t96 * 0.16;
  t18_tmp = t5_tmp * 0.08;
  t19_tmp = t5_tmp * 0.16;
  t20_tmp = t175 * 0.08;
  t21_tmp = t175 * 0.16;
  t22_tmp = t7_tmp * 0.08;
  t23_tmp = t7_tmp * 0.16;
  t47_tmp = t20_tmp - t22_tmp;
  t48_tmp = t21_tmp - t23_tmp;
  t54_tmp = (t19_tmp - t17_tmp) + 0.105;
  t55_tmp = (t18_tmp - t16_tmp) + 0.0525;
  t77_tmp = t48_tmp * t48_tmp + t54_tmp * t54_tmp;
  t174 = t96 * t48_tmp * 0.32 + t175 * t54_tmp * 0.32;
  t7_tmp = t5_tmp * t48_tmp * 0.32 + t7_tmp * t54_tmp * 0.32;
  t48_tmp = 1.0 / (t55_tmp + t77_tmp);
  t54_tmp = t48_tmp * t48_tmp;
  t96 = sqrt((t47_tmp * t47_tmp + t55_tmp * t55_tmp) - t77_tmp * t77_tmp);
  t98_tmp = 1.0 / t96;
  t5_tmp = (t22_tmp - t20_tmp) + t96;
  t120 = atan(t48_tmp * t5_tmp) * 2.0;
  t123_tmp = cos(t120);
  t124_tmp = sin(t120);
  t131_tmp = 1.0 / (t54_tmp * (t5_tmp * t5_tmp) + 1.0);
  t180_tmp =
      (t20_tmp + t174) * t54_tmp * t5_tmp +
      t48_tmp * (t16_tmp - t98_tmp *
                               ((t17_tmp * t47_tmp - t77_tmp * t174 * 2.0) +
                                t175 * t55_tmp * 0.16) /
                               2.0);
  t16_tmp = (t22_tmp + t7_tmp) * t54_tmp * t5_tmp +
            t48_tmp * (t18_tmp - t98_tmp *
                                     ((t19_tmp * t47_tmp + t23_tmp * t55_tmp) -
                                      t77_tmp * t7_tmp * 2.0) /
                                     2.0);
  t20_tmp = t21_tmp + t124_tmp / 4.0;
  t18_tmp = (t17_tmp + t123_tmp / 4.0) - 0.0525;
  t96 = (-t17_tmp - t123_tmp / 4.0) + 0.0525;
  t174 = t96 * t96;
  t175 = 1.0 / t96;
  t96 = t20_tmp * t20_tmp;
  t98_tmp = t123_tmp * t131_tmp;
  t120 = t17_tmp - t98_tmp * t180_tmp / 2.0;
  t54_tmp = t124_tmp * t131_tmp;
  t7_tmp = t21_tmp - t54_tmp * t180_tmp / 2.0;
  t48_tmp = F * (1.0 / sqrt(t96 + t18_tmp * t18_tmp));
  t5_tmp = Tp * t174 * (1.0 / (t96 + t174));
  t96 = t20_tmp * (1.0 / t174);
  T[0] = t48_tmp * (t20_tmp * t120 * 2.0 - t18_tmp * t7_tmp * 2.0) / 2.0 -
         t5_tmp * (t175 * t120 - t96 * t7_tmp);
  T[1] = t48_tmp * (t98_tmp * t20_tmp * t16_tmp - t54_tmp * t18_tmp * t16_tmp) /
             2.0 +
         t5_tmp * (t175 * (0.0 - t98_tmp * t16_tmp / 2.0) +
                   t96 * (t54_tmp * t16_tmp / 2.0));
}

/*
 * File trailer for leg_force.c
 *
 * [EOF]
 */
