/*
 * File: LQR_K.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 2026-05-27 19:29:22
 */

/* Include Files */
#include "LQR_K.h"
#include "LQR_K_data.h"
#include "LQR_K_initialize.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double d;
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    y = fabs(u0);
    d = fabs(u1);
    if (rtIsInf(u1)) {
      if (y == 1.0) {
        y = 1.0;
      } else if (y > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d == 0.0) {
      y = 1.0;
    } else if (d == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L_0)
 *
 * Arguments    : double L_0
 *                double K[12]
 * Return Type  : void
 */
void LQR_K(double L_0, double K[12])
{
  double t2;
  double t3;
  if (!isInitialized_LQR_K) {
    LQR_K_initialize();
  }
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2026-05-27 19:28:41 */
  t2 = L_0 * L_0;
  t3 = rt_powd_snf(L_0, 3.0);
  K[0] = ((L_0 * -91.792661594659236 + t2 * 132.93945170923081) -
          t3 * 91.57829378568988) -
         4.1468526345650751;
  K[1] = ((L_0 * 388.48586167127638 - t2 * 1154.4066798109991) +
          t3 * 1118.1293231595871) +
         37.828885946844508;
  K[2] = ((L_0 * -3.3786513047887792 - t2 * 13.871369806634331) +
          t3 * 12.910570016280071) -
         0.6126296398379586;
  K[3] = ((L_0 * 20.349903316295 - t2 * 12.9469590423793) +
          t3 * 11.86474134653381) +
         9.3827678154065044;
  K[4] = ((L_0 * -4.6857732107189829 + t2 * 1.7467311209938361) +
          t3 * 3.9666081685012471) -
         0.1176921631989062;
  K[5] = ((L_0 * 1.4526210123670951 - t2 * 34.178495130338717) +
          t3 * 42.282191556057732) +
         12.425671140194011;
  K[6] = ((L_0 * -8.16920709391159 - t2 * 2.099012627473706) +
          t3 * 13.325700072116639) -
         0.51368981620637255;
  K[7] = ((L_0 * -13.97544138354743 - t2 * 11.61759623450078) +
          t3 * 26.232842278696062) +
         27.157771873093861;
  K[8] = ((L_0 * -7.2708060095462326 - t2 * 45.673663086129757) +
          t3 * 67.439046782942057) +
         23.790441728250009;
  K[9] = ((L_0 * 315.56536432678 - t2 * 264.86135371480532) -
          t3 * 59.648636911056357) +
         11.70243741303028;
  K[10] = ((L_0 * -18.137967795188771 + t2 * 50.03034155186117) -
           t3 * 43.438359779231639) +
          5.2050857892583116;
  K[11] = ((L_0 * 80.110908587120818 - t2 * 190.95793428982131) +
           t3 * 152.91899140054511) -
          8.2744483261971133;
}

/*
 * File trailer for LQR_K.c
 *
 * [EOF]
 */
