/*
 * File: leg_force.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 2025-09-05 09:37:58
 */

/* Include Files */
#include "leg_force.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_FORCE
 *     T = LEG_FORCE(F,Tp,PHI1,PHI4)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi4
 *                double T[2]
 * Return Type  : void
 */
//由leg_force.m文件转化为c文件，新移植只需要打开文件把函数复制粘贴覆盖这里就好了
void leg_force(double F, double Tp, double phi1, double phi4, double T[2])
{
  double t110;
  double t112_tmp;
  double t118_tmp;
  double t130;
  double t134_tmp;
  double t141_tmp;
  double t16_tmp;
  double t185;
  double t18_tmp;
  double t19_tmp;
  double t20_tmp;
  double t23_tmp;
  double t49_tmp;
  double t50_tmp;
  double t51_tmp;
  double t52_tmp;
  double t5_tmp;
  double t63_tmp;
  double t64_tmp;
  double t65_tmp;
  double t66_tmp;
  double t6_tmp;
  double t7_tmp;
  double t91_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-11-08 15:50:51 */
  t130 = cos(phi1);
  t5_tmp = cos(phi4);
  t6_tmp = sin(phi1);
  t7_tmp = sin(phi4);
  t16_tmp = t130 * 0.21;
  t18_tmp = t130 * 0.105;
  t19_tmp = t5_tmp * 0.105;
  t20_tmp = t6_tmp * 0.21;
  t185 = t6_tmp * 0.105;
  t23_tmp = t7_tmp * 0.105;
  t49_tmp = t16_tmp - t5_tmp * 0.21;
  t50_tmp = t18_tmp - t19_tmp;
  t51_tmp = t20_tmp - t7_tmp * 0.21;
  t52_tmp = t185 - t23_tmp;
  t63_tmp = t6_tmp * t49_tmp * 0.42;
  t64_tmp = t7_tmp * t49_tmp * 0.42;
  t65_tmp = t130 * t51_tmp * 0.42;
  t66_tmp = t5_tmp * t51_tmp * 0.42;
  t91_tmp = t49_tmp * t49_tmp + t51_tmp * t51_tmp;
  t49_tmp = 1.0 / ((t19_tmp - t18_tmp) + t91_tmp);
  t51_tmp = t49_tmp * t49_tmp;
  t110 = sqrt((t50_tmp * t50_tmp + t52_tmp * t52_tmp) - t91_tmp * t91_tmp);
  t112_tmp = 1.0 / t110;
  t118_tmp = (t23_tmp - t185) + t110;
  t130 = atan(t49_tmp * t118_tmp) * 2.0;
  t110 = cos(t130);
  t134_tmp = sin(t130);
  t141_tmp = 1.0 / (t51_tmp * (t118_tmp * t118_tmp) + 1.0);
  t63_tmp =
      t51_tmp * ((t185 + t65_tmp) - t63_tmp) * t118_tmp +
      t49_tmp * (t18_tmp - t112_tmp *
                               ((t16_tmp * t52_tmp + t6_tmp * t50_tmp * -0.21) +
                                t91_tmp * (t63_tmp - t65_tmp) * 2.0) /
                               2.0);
  t65_tmp = t51_tmp * ((t23_tmp + t66_tmp) - t64_tmp) * t118_tmp +
            t49_tmp * (t19_tmp - t112_tmp *
                                     ((t7_tmp * t50_tmp * -0.21 +
                                       t91_tmp * (t64_tmp - t66_tmp) * 2.0) +
                                      t5_tmp * t52_tmp * 0.21) /
                                     2.0);
  t6_tmp = t16_tmp + t110 / 4.0;
  t18_tmp = t20_tmp + t134_tmp / 4.0;
  t130 = t6_tmp * t6_tmp;
  t185 = 1.0 / t6_tmp;
  t118_tmp = t18_tmp * t18_tmp + t130;
  t112_tmp = t110 * t141_tmp;
  t91_tmp = t16_tmp - t112_tmp * t63_tmp / 2.0;
  t110 = t134_tmp * t141_tmp;
  t49_tmp = t20_tmp - t110 * t63_tmp / 2.0;
  t51_tmp = F * (1.0 / sqrt(t118_tmp));
  t118_tmp = Tp * t130 * (1.0 / t118_tmp);
  t130 = t18_tmp * (1.0 / t130);
  T[0] = t51_tmp * (t18_tmp * t91_tmp * 2.0 - t6_tmp * t49_tmp * 2.0) / 2.0 +
         t118_tmp * (t185 * t91_tmp + t130 * t49_tmp);
  T[1] =
      t51_tmp * (t112_tmp * t18_tmp * t65_tmp - t110 * t6_tmp * t65_tmp) / 2.0 -
      t118_tmp * (t185 * (0.0 - t112_tmp * t65_tmp / 2.0) -
                  t130 * (t110 * t65_tmp / 2.0));
}

/*
 * File trailer for leg_force.c
 *
 * [EOF]
 */
