/*
 * File: leg_speed.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 2025-09-05 09:43:37
 */

/* Include Files */
#include "leg_speed.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_SPEED
 *     SPEED = LEG_SPEED(D_PHI1,D_PHI4,PHI1,PHI4)
 *
 * Arguments    : double d_phi1
 *                double d_phi4
 *                double phi1
 *                double phi4
 *                double speed[2]
 * Return Type  : void
 */
 
//由leg_speed.m文件转化为c文件，新移植只需要打开文件把函数复制粘贴覆盖这里就好了
void leg_speed(double d_phi1, double d_phi4, double phi1, double phi4,
               double *d_T,double *d_phi0)
{
  double t10_tmp;
  double t12;
  double t13;
  double t14_tmp;
  double t16;
  double t17;
  double t2;
  double t29;
  double t3;
  double t30;
  double t31;
  double t32;
  double t37;
  double t38;
  double t39;
  double t4;
  double t40;
  double t5;
  double t51;
  double t57;
  double t58;
  double t63;
  double t66;
  double t81;
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-11-08 15:50:50 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t10_tmp = t2 * 0.21;
  t12 = t2 * 0.105;
  t13 = t3 * 0.105;
  t14_tmp = t4 * 0.21;
  t16 = t4 * 0.105;
  t17 = t5 * 0.105;
  t29 = t10_tmp - t3 * 0.21;
  t30 = t12 - t13;
  t31 = t14_tmp - t5 * 0.21;
  t32 = t16 - t17;
  t37 = t4 * t29 * 0.42;
  t38 = t5 * t29 * 0.42;
  t39 = t2 * t31 * 0.42;
  t40 = t3 * t31 * 0.42;
  t51 = t29 * t29 + t31 * t31;
  t57 = 1.0 / ((t13 - t12) + t51);
  t58 = t57 * t57;
  t2 = sqrt((t30 * t30 + t32 * t32) - t51 * t51);
  t63 = 1.0 / t2;
  t66 = (t17 - t16) + t2;
  t2 = atan(t57 * t66) * 2.0;
  t29 = cos(t2);
  t31 = sin(t2);
  t81 = 1.0 / (t58 * (t66 * t66) + 1.0);
  t16 = t58 * ((t16 + t39) - t37) * t66 +
        t57 * (t12 - t63 *
                         ((t10_tmp * t32 + t4 * t30 * -0.21) +
                          t51 * (t37 - t39) * 2.0) /
                         2.0);
  t2 = t58 * ((t17 + t40) - t38) * t66 +
       t57 * (t13 - t63 *
                        ((t5 * t30 * -0.21 + t51 * (t38 - t40) * 2.0) +
                         t3 * t32 * 0.21) /
                        2.0);
  t39 = t10_tmp + t29 / 4.0;
  t4 = t14_tmp + t31 / 4.0;
  t51 = t29 * t81;
  t12 = t51 * t2;
  t31 *= t81;
  t57 = t31 * t2;
  t58 = t39 * t39;
  t63 = 1.0 / t39;
  t29 = t4 * t4 + t58;
  t2 = 1.0 / sqrt(t29);
  t66 = 1.0 / t29;
  t51 = t10_tmp - t51 * t16 / 2.0;
  t29 = t14_tmp - t31 * t16 / 2.0;
  *d_T = d_phi4 * t2 * (t4 * t12 - t39 * t57) / 2.0 +
             d_phi1 * t2 * (t4 * t51 * 2.0 - t39 * t29 * 2.0) / 2.0;
  t2 = t4 * (1.0 / t58);
  *d_phi0 = d_phi1 * t58 * t66 * (t63 * t51 + t2 * t29) -
             d_phi4 * t58 * t66 * (t63 * (0.0 - t12 / 2.0) - t2 * (t57 / 2.0));
}

/*
 * File trailer for leg_speed.c
 *
 * [EOF]
 */
