/*
 * File: leg_position.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 2025-09-05 09:42:16
 */

/* Include Files */
#include "leg_position.h"
#include <math.h>
#include "inttypes.h"
#include "user_lib.h"
#include "arm_math.h"
/* Function Definitions */
/*
 * LEG_POSITION
 *     POSITION = LEG_POSITION(PHI1,PHI4)
 *
 * Arguments    : double phi1
 *                double phi4
 *                double position[2]
 * Return Type  : void
 */
 typedef double real_T;
 typedef uint8_t boolean_T;
 #define RT_PI 3.14159265358979323846
 static real_T rtNaN;
 static real_T rtInf;
 static real_T rtMinusInf;

 static boolean_T rtIsNaN(real_T value)
{
  return ((value != value) ? 1 : 0);
}
 
static boolean_T rtIsInf(real_T value)
{
  return ((value == rtInf || value == rtMinusInf) ? 1 : 0);
}

 double b_atan2(double y, double x)
{
  double r;
  int i;
  int i1;
  if (rtIsNaN(y) || rtIsNaN(x)) {
    r = rtNaN;
  } else if (rtIsInf(y) && rtIsInf(x)) {
    if (y > 0.0) {
      i = 1;
    } else {
      i = -1;
    }
    if (x > 0.0) {
      i1 = 1;
    } else {
      i1 = -1;
    }
    r = atan2(i, i1);
  } else if (x == 0.0) {
    if (y > 0.0) {
      r = RT_PI / 2.0;
    } else if (y < 0.0) {
      r = -(RT_PI / 2.0);
    } else {
      r = 0.0;
    }
  } else {
    r = atan2(y, x);
  }
  return r;
}

//由leg_position.m文件转化为c文件，新移植只需要打开文件把函数复制粘贴覆盖这里就好了
void leg_position(double phi1, double phi4, double *L,double *phi0)
{
  double a;
  double t10;
  double t12;
  double t13;
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t8;
  double t9;

  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-11-08 15:50:50 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.21;
  t8 = t2 * 0.105;
  t9 = t3 * 0.105;
  t10 = t4 * 0.21;
  t12 = t4 * 0.105;
  t13 = t5 * 0.105;
  t4 = t6 - t3 * 0.21;
  a = t8 - t9;
  t2 = t10 - t5 * 0.21;
  t3 = t12 - t13;
  t2 = t4 * t4 + t2 * t2;
  t2 = atan(1.0 / ((t9 - t8) + t2) *
            ((t13 - t12) + sqrt((a * a + t3 * t3) - t2 * t2))) *
       2.0;
  t4 = t10 + sin(t2) / 4.0;
  t2 = t6 + cos(t2) / 4.0;
  *L = sqrt(t4 * t4 + t2 * t2);
  *phi0 = b_atan2(t4, t2);
}

/*
 * File trailer for leg_position.c
 *
 * [EOF]
 */
//
void JointToLeg(float phi1, float phi4, float *L, float *phi0)
{
	float a=0.1138;
	float b=0.135;
	float L1;
	float B=(phi1-phi4)/2;
	float c1,c2,L3;

	c1=a*arm_cos_f32(B)+fast_sqrt(b*b-a*a*arm_sin_f32(B)*arm_sin_f32(B));
	c2=a*arm_cos_f32(B)-fast_sqrt(b*b-a*a*arm_sin_f32(B)*arm_sin_f32(B));
	L3=(c1>0?c1:c2);
	
	*L=L3*L1/a;//有bug，L一直为零，还是用matlab解算的
	*phi0=rad_format((phi1+phi4)/2);
}

//由末端逆解到关节电机角度，用于自启用，给我自启时直接关节电机角度PID控制
void LegToJoint(float L_0,float phi_0,float *phi_1,float *phi_4)
{
	float L1=0.21;
	float a=0.1138;
	float b=0.135;
	float c,B;
		
	c=L_0/L1*a;
	B=acos((a*a+c*c-b*b)/(2*a*c));
	
	*phi_1=rad_format(phi_0+B);
	*phi_4=rad_format(phi_0-B);
	
}
