/*
 * File: leg_speed.c
 *
 * MATLAB Coder version            : 24.2
 * C/C++ source code generated on  : 2025-12-14 14:57:16
 */

/* Include Files */
#include "leg_speed.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_SPEED
 *     SPEED = LEG_SPEED(D_PHI1,D_PHI4,PHI1,PHI4)
 *
 * Arguments    : double d_phi1
 *                double d_phi4
 *                double phi1
 *                double phi4
 *                double speed[2]
 * Return Type  : void
 */
void leg_speed(double d_phi1, double d_phi4, double phi1, double phi4,
               double speed[2])
{
  double t10;
  double t106;
  double t11_tmp;
  double t12;
  double t13;
  double t14;
  double t15_tmp;
  double t16;
  double t17;
  double t2;
  double t28;
  double t29;
  double t3;
  double t32;
  double t33;
  double t4;
  double t44;
  double t47;
  double t5;
  double t56;
  double t70;
  double t71;
  double t76;
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     2025-12-14 14:52:54 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t10 = t2 * 0.08;
  t11_tmp = t2 * 0.16;
  t12 = t3 * 0.08;
  t13 = t3 * 0.16;
  t14 = t4 * 0.08;
  t15_tmp = t4 * 0.16;
  t16 = t5 * 0.08;
  t17 = t5 * 0.16;
  t28 = t14 - t16;
  t29 = t15_tmp - t17;
  t32 = (t13 - t11_tmp) + 0.105;
  t33 = (t12 - t10) + 0.0525;
  t44 = t29 * t29 + t32 * t32;
  t47 = t2 * t29 * 0.32 + t4 * t32 * 0.32;
  t5 = t3 * t29 * 0.32 + t5 * t32 * 0.32;
  t29 = 1.0 / (t33 + t44);
  t32 = t29 * t29;
  t2 = sqrt((t28 * t28 + t33 * t33) - t44 * t44);
  t56 = 1.0 / t2;
  t3 = (t16 - t14) + t2;
  t2 = atan(t29 * t3) * 2.0;
  t70 = cos(t2);
  t71 = sin(t2);
  t76 = 1.0 / (t32 * (t3 * t3) + 1.0);
  t106 =
      (t14 + t47) * t32 * t3 +
      t29 * (t10 -
             t56 * ((t11_tmp * t28 - t44 * t47 * 2.0) + t4 * t33 * 0.16) / 2.0);
  t2 = (t16 + t5) * t32 * t3 +
       t29 * (t12 - t56 * ((t13 * t28 + t17 * t33) - t44 * t5 * 2.0) / 2.0);
  t4 = t15_tmp + t71 / 4.0;
  t10 = (t11_tmp + t70 / 4.0) - 0.0525;
  t5 = t70 * t76;
  t14 = t5 * t2;
  t56 = t71 * t76;
  t71 = t56 * t2;
  t2 = (-t11_tmp - t70 / 4.0) + 0.0525;
  t47 = t2 * t2;
  t32 = 1.0 / t2;
  t3 = t4 * t4;
  t2 = 1.0 / sqrt(t3 + t10 * t10);
  t29 = 1.0 / (t3 + t47);
  t5 = t11_tmp - t5 * t106 / 2.0;
  t3 = t15_tmp - t56 * t106 / 2.0;
  speed[0] = d_phi4 * t2 * (t4 * t14 - t10 * t71) / 2.0 +
             d_phi1 * t2 * (t4 * t5 * 2.0 - t10 * t3 * 2.0) / 2.0;
  t2 = t4 * (1.0 / t47);
  speed[1] = -d_phi1 * t47 * t29 * (t32 * t5 - t2 * t3) +
             d_phi4 * t47 * t29 * (t32 * (0.0 - t14 / 2.0) + t2 * (t71 / 2.0));
}

/*
 * File trailer for leg_speed.c
 *
 * [EOF]
 */
